const portfolioProjects = [
  {
    id: 'bpillar',
    title: 'B-Pillar Trim Design',
    shortTitle: 'B-Pillar Trim',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Class A / B / C surfacing',
    thumbnail: 'ppt/B_PILLER.png',
    presentation: 'ppt/B_PILLER.pptx',
    deck: '15-slide design report',
    summary: 'A production-minded trim study that moves from master sections into a fully resolved plastic part.',
    objective: 'Develop a B-pillar trim with controlled surface transitions, attachment logic, and the surrounding package in view.',
    workflow: ['Master section review', 'A-surface refinement', 'B-side feature planning', 'C-surface closure', 'Package and clearance review'],
    outputs: ['A-, B-, and C-surface development', 'B-side attachment features', 'Surrounding-part packaging', 'Closed-volume design intent'],
    tools: ['CATIA V5', 'Surface design', 'Plastic part design'],
    accent: 'cyan'
  },
  {
    id: 'cupholder',
    title: 'Cup Holder Trim Design',
    shortTitle: 'Cup Holder Trim',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Interior trim development',
    thumbnail: 'ppt/CUP__HOLDER.png',
    presentation: 'ppt/CUP_HOLDER.pptx',
    deck: '16-slide design report',
    summary: 'An interior trim case study balancing user-facing Class-A surfaces with practical attachment and packaging decisions.',
    objective: 'Build a complete cup-holder trim concept with clean surface development and manufacturable supporting geometry.',
    workflow: ['Surface intake', 'Class-A clean-up', 'Thickness and offset strategy', 'Attachment detailing', 'Final trim review'],
    outputs: ['Surface refinement', 'Attachment-feature detailing', 'Environmental packaging', 'Trim-ready presentation deck'],
    tools: ['CATIA V5', 'Class-A surfacing', 'Design for manufacturing'],
    accent: 'violet'
  },
  {
    id: 'bumper',
    title: 'Front Bumper Fascia',
    shortTitle: 'Front Bumper',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Exterior component design',
    thumbnail: 'thumnail/bumper.png',
    presentation: 'ppt/Front Bumper  Design Report.pptx',
    deck: '11-slide design report',
    summary: 'A fascia development workflow covering surface quality, closed-volume construction, and clearance validation.',
    objective: 'Take the supplied Class-A surface through a structured plastic-part workflow and close it into a viable fascia concept.',
    workflow: ['Class-A surface audit', 'Tooling direction check', 'Curvature review', 'B/C surface development', 'Trim and solid conversion'],
    outputs: ['Front bumper Class-A review', 'Tooling-axis study', 'B- and C-surface development', 'Closed solid conversion'],
    tools: ['CATIA V5', 'Draft analysis', 'Curvature analysis'],
    accent: 'orange'
  },
  {
    id: 'air',
    title: 'Airbag Cover Design',
    shortTitle: 'Airbag Cover',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Safety-adjacent trim design',
    thumbnail: 'thumnail/airbag.png',
    presentation: 'ppt/Airbag Cover Design Report.pptx',
    deck: '9-slide design report',
    summary: 'A compact case study in surface quality, draft direction, radius review, and closed-volume completion.',
    objective: 'Translate a supplied Class-A surface into an airbag-cover form with a clear and repeatable manufacturing workflow.',
    workflow: ['Surface import and audit', 'Tooling-axis creation', 'Draft and radius checks', 'B/C surface build', 'Final trim and solid'],
    outputs: ['Class-A surface analysis', 'Draft-angle review', 'Curvature/radius check', 'Closed solid part'],
    tools: ['CATIA V5', 'Plastic part design', 'Manufacturability review'],
    accent: 'rose'
  },
  {
    id: 'support',
    title: 'Switch Support Design',
    shortTitle: 'Switch Support',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Support component design',
    thumbnail: 'thumnail/switch_support.png',
    presentation: 'ppt/Switch Support Design Report.pptx',
    deck: '11-slide design report',
    summary: 'A support-component workflow focused on surface repair, draft direction, thickness strategy, and feature closure.',
    objective: 'Create a switch-support component that is both visually controlled on the outside and logically structured on the B-side.',
    workflow: ['Surface repair', 'Normal-to-surface tooling direction', 'Curvature review', 'Offset and thickness', 'Feature and trim closure'],
    outputs: ['Surface modification', 'Tooling direction study', '2.5 mm thickness strategy', 'C-surface and solid conversion'],
    tools: ['CATIA V5', 'Offset surfaces', 'Draft analysis'],
    accent: 'blue'
  },
  {
    id: 'sidetrim',
    title: 'Seat Recliner Side Trim',
    shortTitle: 'Seat Side Trim',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Interior trim development',
    thumbnail: 'thumnail/side.png',
    presentation: 'ppt/Seat Recliner Side Trim Design Report.pptx',
    deck: '11-slide design report',
    summary: 'An interior-side trim study showing how surface inputs become a structured, clearance-aware plastic component.',
    objective: 'Develop the side trim around a clear Class-A/B/C surface strategy with the surrounding seat environment considered.',
    workflow: ['Surface assessment', 'Tooling and draft review', 'Curvature check', 'B-side offset', 'C-surface and solid closure'],
    outputs: ['Trim surface development', 'Clearance-line definition', 'B-side thickness strategy', 'Closed-volume design'],
    tools: ['CATIA V5', 'Surface modeling', 'Clearance review'],
    accent: 'teal'
  },
  {
    id: 'feature',
    title: 'B-Surface Features',
    shortTitle: 'B-Surface Features',
    category: 'plastic',
    categoryLabel: 'Feature engineering',
    discipline: 'Attachment and tooling features',
    thumbnail: 'thumnail/feature.png',
    presentation: 'ppt/Clip_Tower.pptx',
    deck: '17-slide feature report',
    summary: 'A focused look at the practical B-side features that make a plastic part attachable, serviceable, and toolable.',
    objective: 'Document clip-tower and supporting feature logic with enough clarity for a design review conversation.',
    workflow: ['Feature intent', 'Draft direction', 'Clip-tower construction', 'Support geometry', 'Review-ready documentation'],
    outputs: ['Clip-tower concepts', 'B-side supporting geometry', 'Draft-conscious feature design', 'Feature documentation'],
    tools: ['CATIA V5', 'B-surface features', 'Tooling feasibility'],
    accent: 'purple'
  },
  {
    id: 'doghouse',
    title: 'Doghouse Feature Study',
    shortTitle: 'Doghouse Study',
    category: 'plastic',
    categoryLabel: 'Feature engineering',
    discipline: 'B-side attachment design',
    thumbnail: 'ppt/DHF.png',
    presentation: 'ppt/DOGHOUSE.pptx',
    deck: '5-slide feature deck',
    summary: 'A compact feature study dedicated to the geometry and intent of a plastic-part doghouse.',
    objective: 'Explore a clean, reviewable doghouse feature with a direct connection to attachment and molding intent.',
    workflow: ['Feature definition', 'Section strategy', 'Draft-conscious geometry', 'Support review'],
    outputs: ['Doghouse feature study', 'Feature section logic', 'B-side design intent'],
    tools: ['CAD modeling', 'Plastic features', 'Design review'],
    accent: 'indigo'
  },
  {
    id: 'fbcover',
    title: 'Fuse Box Cover Design',
    shortTitle: 'Fuse Box Cover',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'DFM-led plastic design',
    thumbnail: 'thumnail/fusebox.png',
    presentation: 'fusebox.pptx',
    deck: 'Design report',
    summary: 'A manufacturability-led component study built around tooling axis, draft, radius, and Class-A/B/C surface decisions.',
    objective: 'Design an automotive fuse-box cover from the supplied Class-A surface and validate the major molding constraints.',
    workflow: ['Class-A surface analysis', 'Tooling-axis creation', 'Draft-angle validation', 'Curvature review', 'Closed-surface to solid'],
    outputs: ['Tooling-axis study', 'Draft analysis', 'ECE R21 radius review', 'B/C surface development', 'Solid conversion'],
    tools: ['CATIA V5', 'DFM review', 'Draft and curvature analysis'],
    accent: 'amber'
  },
  {
    id: 'fbcov',
    title: 'Fuse Box Cover: Detail Report',
    shortTitle: 'Fuse Box Detail',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Detailed component report',
    thumbnail: 'thumnail/fusebox.png',
    presentation: 'ppt/Fuseboxcov.pptx',
    deck: 'Design report',
    summary: 'A second fuse-box documentation set that exposes the design decisions and checks behind the final part.',
    objective: 'Present the design logic, validation steps, and final feature completion in a concise technical format.',
    workflow: ['Input review', 'Surface strategy', 'Draft and radius checks', 'Feature completion', 'Final review'],
    outputs: ['Detailed design workflow', 'Manufacturability checkpoints', 'Final component documentation'],
    tools: ['Plastic part design', 'DFM', 'Technical documentation'],
    accent: 'yellow'
  },
  {
    id: 'centralbezel',
    title: 'Center Bezel Design',
    shortTitle: 'Center Bezel',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Interior trim development',
    thumbnail: 'thumnail/central.png',
    presentation: 'ppt/Center Bezel Design Report.pptx',
    deck: '15-slide design report',
    summary: 'An interior bezel workflow bringing together clean visual surfaces, draft-conscious construction, and attachment intent.',
    objective: 'Develop a center bezel trim component through the same disciplined A/B/C surface workflow used in production programs.',
    workflow: ['Surface audit', 'Tooling direction', 'Class-A modification', 'B/C surface development', 'Solid and review'],
    outputs: ['A-surface modification', 'B-surface thickness strategy', 'C-surface closure', 'Final solid design'],
    tools: ['CATIA V5', 'Interior trim', 'Surface design'],
    accent: 'sky'
  },
  {
    id: 'ac',
    title: 'AC Front Control Panel',
    shortTitle: 'AC Control Panel',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Control-panel design',
    thumbnail: 'thumnail/ac.png',
    presentation: 'ppt/AC Front Control Panel Design Report.pptx',
    deck: '10-slide design report',
    summary: 'A control-panel case study documenting surface repair, draft direction, curvature checks, and part closure.',
    objective: 'Create a robust front control panel from a Class-A input while maintaining the intent of the visible surface.',
    workflow: ['Tangency issue identification', 'A-surface repair', 'Tooling-axis creation', 'Draft and curvature analysis', 'B/C closure'],
    outputs: ['Repaired Class-A surface', 'Tooling-axis decision', 'Draft review', 'Final trim-to-solid workflow'],
    tools: ['CATIA V5', 'Shape fillet', 'Draft analysis'],
    accent: 'cyan'
  },
  {
    id: 'autoswitch',
    title: 'Auto Switch Design',
    shortTitle: 'Auto Switch',
    category: 'plastic',
    categoryLabel: 'Automotive plastics',
    discipline: 'Switch trim development',
    thumbnail: 'thumnail/switch.png',
    presentation: 'ppt/Auto Switch Design Report.pptx',
    deck: '9-slide design report',
    summary: 'A compact switch-cover workflow demonstrating how a small visible component can still require a full surface-to-solid process.',
    objective: 'Design a switch-cover trim component with clear surface quality, draft logic, and a complete closed volume.',
    workflow: ['A-surface clean-up', 'Tooling direction', 'Draft and radius review', 'B/C surface development', 'Solid conversion'],
    outputs: ['Surface repair', 'Draft-angle validation', 'Clearance-conscious closure', 'Final solid component'],
    tools: ['CATIA V5', 'Plastic part design', 'Surface analysis'],
    accent: 'fuchsia'
  },
  {
    id: 'automotive',
    title: 'High-Performance Automotive Modeling',
    shortTitle: 'Automotive Modeling',
    category: 'surface',
    categoryLabel: 'Surface & geometry',
    discipline: 'Advanced surfacing',
    thumbnail: 'SURFACE DESIGN/Screenshot 2026-05-02 022658.png',
    presentation: 'ppt/modeling.pptx',
    deck: '7-slide modeling report',
    summary: 'A geometry-led study of vehicle components and body-panel surfacing with an emphasis on form, continuity, and precision.',
    objective: 'Showcase advanced automotive modeling capability beyond individual trim parts.',
    workflow: ['Reference interpretation', 'Surface construction', 'Continuity review', 'Geometric refinement', 'Design presentation'],
    outputs: ['Automotive surface studies', 'Body-panel geometry', 'High-quality visual form development'],
    tools: ['Siemens NX', 'CATIA V5', 'Surface modeling'],
    accent: 'blue'
  },
  {
    id: 'beproject',
    title: 'Pneumatic Scraper Blade for CNC Laser-Bed Cleaning',
    shortTitle: 'Pneumatic Scraper Blade',
    category: 'mechanical',
    categoryLabel: 'Mechanical systems',
    discipline: 'Academic capstone project',
    thumbnail: 'thumnail/Screenshot 2026-04-18 161628.png',
    presentation: 'ppt/beproject.pptx',
    deck: '26-slide project report',
    summary: 'A complete mechanical-system project that converts a repetitive, unsafe cleaning task into a compact pneumatic mechanism.',
    objective: 'Design a safe, reliable, and low-cost scraper system to remove slag and dust from CNC laser cutting beds.',
    workflow: ['Problem framing', 'Literature and material review', 'Cylinder calculations', '3D design and simulation', 'Fabrication and testing'],
    outputs: ['Pneumatic mechanism concept', 'Design calculations', '3D assembly and simulation', 'Fabricated-component documentation', 'Working configuration'],
    tools: ['3D CAD', 'Pneumatics', 'Mechanical design', 'Simulation'],
    accent: 'green'
  },
  {
    id: 'thermal',
    title: 'Thermal Optimization of Truck Wheel Rim',
    shortTitle: 'Truck Wheel Rim',
    category: 'analysis',
    categoryLabel: 'CFD & analysis',
    discipline: 'Thermal optimization',
    thumbnail: 'thumnail/rim.png',
    presentation: 'ppt/tim.pptx',
    deck: '3-slide analysis deck',
    summary: 'A focused analysis project connecting wheel-rim geometry with thermal performance and airflow intent.',
    objective: 'Investigate thermal behavior and improve heat dissipation through informed wheel-rim modeling.',
    workflow: ['Geometry preparation', 'Boundary-condition thinking', 'Thermal analysis', 'Design refinement', 'Result communication'],
    outputs: ['Wheel-rim geometry', 'Thermal optimization direction', 'Analysis-focused presentation'],
    tools: ['CFD analysis', 'Thermal modeling', '3D CAD'],
    accent: 'red'
  }
];

function presentationViewerUrl(path) {
  const absoluteUrl = `https://devborase.github.io/dev-portfolio/${path}`;
  return `https://docs.google.com/gview?url=${encodeURIComponent(absoluteUrl)}&embedded=true`;
}

window.portfolioProjects = portfolioProjects;
window.presentationViewerUrl = presentationViewerUrl;
